# Generated by Django 4.2.4 on 2023-08-12 08:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namn', models.CharField(max_length=255, verbose_name='Namn')),
                ('beskrivning', models.TextField(verbose_name='Beskrivning')),
                ('typ', models.CharField(choices=[('rum', 'Rum'), ('utrustning', 'Utrustning')], default='rum', max_length=50, verbose_name='Typ')),
                ('tillgänglighet', models.TextField(blank=True, null=True, verbose_name='Tillgänglighet')),
            ],
        ),
        migrations.CreateModel(
            name='Bokning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starttid', models.DateTimeField(verbose_name='Starttid')),
                ('sluttid', models.DateTimeField(verbose_name='Sluttid')),
                ('status', models.CharField(choices=[('planerad', 'Planerad'), ('genomförd', 'Genomförd'), ('avbokad', 'Avbokad')], default='planerad', max_length=50, verbose_name='Status')),
                ('kommentarer', models.TextField(blank=True, null=True, verbose_name='Kommentarer')),
                ('användare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Användare')),
                ('resurs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.resurs', verbose_name='Resurs')),
            ],
        ),
    ]
