# Generated by Django 4.2.4 on 2023-08-12 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookings', '0002_resurs_pris_resurs_valuta_resurs_varaktighet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Start Time')),
                ('end_time', models.DateTimeField(verbose_name='End Time')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('conducted', 'Conducted'), ('cancelled', 'Cancelled')], default='scheduled', max_length=50, verbose_name='Status')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Comments')),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('type', models.CharField(choices=[('room', 'Room'), ('equipment', 'Equipment')], default='room', max_length=50, verbose_name='Type')),
                ('availability', models.TextField(blank=True, null=True, verbose_name='Availability')),
                ('duration', models.IntegerField(verbose_name='Duration')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('currency', models.CharField(default='SEK', max_length=50, verbose_name='Currency')),
            ],
        ),
        migrations.DeleteModel(
            name='Bokning',
        ),
        migrations.DeleteModel(
            name='Resurs',
        ),
        migrations.AddField(
            model_name='booking',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.resource', verbose_name='Resource'),
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
