# Generated by Django 4.2.4 on 2023-08-15 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_resource_type_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='duration',
        ),
        migrations.AddField(
            model_name='resource',
            name='max_capacity',
            field=models.IntegerField(default=8, verbose_name='Maximum Capacity'),
        ),
        migrations.AddField(
            model_name='resource',
            name='min_capacity',
            field=models.IntegerField(default=2, verbose_name='Minimum Capacity'),
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Start Time')),
                ('available_slots', models.IntegerField(default=0, verbose_name='Available Slots')),
                ('end_time', models.DateTimeField(verbose_name='End Time')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.resource', verbose_name='Resource')),
            ],
        ),
    ]
